model {
  file: "model.sdf"
}
name: "Marvel_Avengers_Titan_Hero_Series_Doctor_Doom"
description: "Marvel Avengers Titan Hero Series, Doctor Doom"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Hasbro"
}
annotations {
  key: "gtin"
  value: "00653569981916"
}
annotations {
  key: "sku"
  value: "653569981916"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Action Figures"
}
